apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: ci-cd-pipeline
spec:
  workspaces:
    - name: output

  tasks:
    - name: cleanup
      taskRef:
        name: cleanup
      workspaces:
        - name: source
          workspace: output

    - name: eslint
      runAfter: ["cleanup"]
      taskRef:
        name: eslint
      workspaces:
        - name: source
          workspace: output

    - name: jest-test
      runAfter: ["eslint"]
      taskRef:
        name: jest-test
      workspaces:
        - name: source
          workspace: output

    - name: deploy
      runAfter: ["jest-test"]
      taskRef:
        name: openshift-client
      params:
        - name: SCRIPT
          value: |
            echo "SERVICERUNNING"
            echo "Server running on port 8000"
